#!/bin/bash
# GUARD - LCP
# author: Alex Carrega <alessandro.carrega@cnit.it>

# Start the lcp

export COMPONENT=lcp
export VERSION=master
export PROJECT=guard
export INSTALLATION_PATH=~/GUARD/Development/Integration/lcp

export TMP_PATH=/tmp
export PIDFILE=$TMP_PATH/$COMPONENT.pid

export LCP_HOST=0.0.0.0
export LCP_PORT=4000
export LCP_AUTH_MAX_TTL=10min
export LCP_POLYCUBE_HOST=127.0.0.1
export LCP_POLYCUBE_PORT=9000
export LCP_POLYCUBE_TIMEOUT=20s
export LCP_DEV_USERNAME=lcp
# Password: "guard" hashed in sha256
export LCP_DEV_PASSWORD=a9d4034da07d8ef31db1cd4119b6a4552fdfbd19787e2848e71c8ee3b47703a7
export LCP_LOG_LEVEL=DEBUG

source ~/.venv/lcp/bin/activate

if [ -f $PIDFILE ] ; then
    echo "Error: $COMPONENT already started"
    echo "Note: to force the start please remove $PIDFILE"
else
    cd $INSTALLATION_PATH
    python3 main.py &
    echo $! > $PIDFILE
fi
